
workflows:
  android-debug:
    name: Build Android APK (Debug)
    environment:
      flutter: stable
    scripts:
      - name: Build debug APK
        script: |
          flutter pub get
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
